# Generated by Django 6.0.6 on 2026-09-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_mart', '0003_existingdebt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alternative_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alternative_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alternative_unit_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.CharField(default='Unit', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='has_alternative_unit',
            field=models.BooleanField(default=False),
        ),
    ]
